"""
Extract KBDU noise-abatement polygons from DenverMetro_v6_April-2025.kml
and write them to noise/web/src/noiseZones.js.

Usage:
  py import_kml.py [path/to/DenverMetro_v6_April-2025.kml]

Picks up every <Placemark> whose <name> contains "Noise Abatement" (or
"Pattern") inside the KBDU folder, parses the outer LinearRing, and emits
a JS module compatible with the React app.
"""
import os, re, sys, xml.etree.ElementTree as ET

DEFAULT_KML = r"C:\Users\Benja\Downloads\DenverMetro_v6_April-2025.kml"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "web", "src", "noiseZones.js")
NS = {"k": "http://www.opengis.net/kml/2.2"}

def parse_coords(text):
    pts = []
    for tok in text.strip().split():
        parts = tok.split(",")
        if len(parts) < 2:
            continue
        lon, lat = float(parts[0]), float(parts[1])
        pts.append([round(lat, 6), round(lon, 6)])
    return pts

def extract_polygons(pm):
    out = []
    for poly in pm.findall(".//k:Polygon", NS):
        ring = poly.find(".//k:outerBoundaryIs/k:LinearRing/k:coordinates", NS)
        if ring is not None and ring.text:
            out.append(parse_coords(ring.text))
    return out

def main():
    kml_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_KML
    if not os.path.exists(kml_path):
        print(f"KML not found: {kml_path}"); sys.exit(1)

    tree = ET.parse(kml_path)
    root = tree.getroot()

    # Scan ALL airport folders for noise-abatement placemarks. Skip
    # pattern boxes and glider boxes — those are operational, not noise.
    SKIP_NAMES = {"pattern", "glider box"}
    AIRPORT_FOLDERS = {"KBDU", "KAPA", "KBJC", "KEIK", "KLMO", "KGXY"}
    zones = []
    for f in root.iter("{http://www.opengis.net/kml/2.2}Folder"):
        folder_name_el = f.find("k:name", NS)
        if folder_name_el is None:
            continue
        folder_name = (folder_name_el.text or "").strip()
        # Match airport folders (exact) or the top-level CO folder
        if folder_name not in AIRPORT_FOLDERS and folder_name != "CO":
            continue
        # Determine airport prefix for labeling
        airport = folder_name if folder_name in AIRPORT_FOLDERS else ""
        for pm in f.findall("k:Placemark", NS):  # direct children only
            name_el = pm.find("k:name", NS)
            if name_el is None:
                continue
            name = (name_el.text or "").strip()
            # Skip pattern boxes and glider boxes
            if any(skip in name.lower() for skip in SKIP_NAMES):
                continue
            desc_el = pm.find("k:description", NS)
            desc = (desc_el.text or "").strip() if desc_el is not None else ""
            polys = extract_polygons(pm)
            if not polys:
                continue
            for pi, poly in enumerate(polys):
                if len(poly) < 3:
                    continue
                prefix = f"{airport} " if airport else ""
                label = f"{prefix}{name}" if len(polys) == 1 else f"{prefix}{name} #{pi+1}"
                zones.append({"name": label.strip(), "note": desc or f"{airport or 'CO'} noise abatement", "polygon": poly})

    print(f"Parsed {len(zones)} KBDU noise-abatement polygons")
    for i, z in enumerate(zones):
        print(f"  [{i}] {z['name']} — {len(z['polygon'])} verts")

    header = (
        "// Auto-generated by noise/import_kml.py from\n"
        "// DenverMetro_v6_April-2025.kml (KBDU folder, 'Noise Abatement' placemarks).\n"
        "// Edit import_kml.py and re-run instead of hand-editing this file.\n\n"
        "export const NOISE_ZONES = "
    )
    body = "[\n"
    for z in zones:
        body += "  {\n"
        body += f"    name: {z['name']!r},\n"
        body += f"    note: {z['note']!r},\n"
        body += "    polygon: [\n"
        for lat, lon in z["polygon"]:
            body += f"      [{lat}, {lon}],\n"
        body += "    ],\n"
        body += "  },\n"
    body += "]\n"
    with open(OUT, "w") as fh:
        fh.write(header + body)
    print(f"\nwrote {OUT}")

if __name__ == "__main__":
    main()
